prgrms-web-devcourse-final-project/WEB6_8_Bid_BE

src/main/java/com/backend/domain/bid/controller/ApiV1BidController.java
src/main/java/com/backend/domain/bid/dto/MyBidResponseDto.java
src/main/java/com/backend/domain/bid/repository/BidRepository.java
src/main/java/com/backend/domain/bid/service/BidService.java
src/test/java/com/backend/domain/bid/controller/ApiV1BidControllerTest.java
src/test/java/com/backend/domain/bid/service/BidServiceTest.java

내 입찰내역 api 구현
입찰 api 및 서비스 테스트 코드 구현

[Feat]: 내 입찰 내역 조회 기능 구현 및 테스트 추가

---

src/main/java/com/backend/domain/notification/controller/ApiV1NotificationController.java
src/main/java/com/backend/domain/notification/dto/NotificationListResponseDto.java
src/main/java/com/backend/domain/notification/entity/Notification.java
src/main/java/com/backend/domain/notification/repository/NotificationRepository.java
src/main/java/com/backend/domain/notification/service/NotificationService.java

알림 관린 Dto/Service/Repository/Controller 작성

[Feat]:  알림 목록 조회 기능 구현

---

src/main/java/com/backend/domain/product/controller/ApiV1ProductController.java
src/main/java/com/backend/domain/product/controller/ApiV1ProductControllerDocs.java
src/main/java/com/backend/domain/product/dto/ProductCreateRequest.java
src/main/java/com/backend/domain/product/dto/ProductModifyRequest.java
src/main/java/com/backend/domain/product/entity/Product.java
src/main/java/com/backend/domain/product/entity/ProductImage.java
src/main/java/com/backend/domain/product/service/ProductService.java
src/main/java/com/backend/global/initData/TestInitData.java
src/main/java/com/backend/global/jpa/entity/BaseEntity.java
src/main/resources/application.yml
src/test/java/com/backend/domain/product/controller/ApiV1ProductControllerTest.java
src/test/java/com/backend/domain/product/service/ProductServiceTest.java

- 상품 수정 기능 구현
- 컨트롤러 테스트, 서비스 테스트 작성/통과
- Swagger 문서화
- 이미지 처리, getStatus 개선
Closes #23 
- 인증/인가 로직은 아직 주석처리 해놓았습니다
- BaseEntity의 equals 로직 개선했습니다

[Feat]: 상품 수정 기능 구현

---

src/main/java/com/backend/domain/bid/controller/ApiV1BidController.java
src/main/java/com/backend/domain/bid/service/BidService.java
src/main/java/com/backend/global/initData/BaseInitData.java
src/main/java/com/backend/global/security/JwtAuthenticationFilter.java
src/main/java/com/backend/global/security/SecurityConfig.java
src/main/java/com/backend/global/webSocket/service/WebSocketService.java
src/main/resources/static/bid-test.html
src/main/resources/static/websocket-test.html

실시간 입찰 브로드캐스팅 로직 추가
BaseinitData에 초기 값들 설정
테스트용 설정 추가(jwtfilter, securityConfig,BidController)
테스트용 html 구현

[Feat]: 실시간 입찰 브로드캐스팅 구현

---

src/main/java/com/backend/domain/product/controller/ApiV1ProductController.java
src/main/java/com/backend/domain/product/controller/ApiV1ProductControllerDocs.java
src/main/java/com/backend/domain/product/entity/Product.java
src/main/java/com/backend/domain/product/service/ProductService.java
src/main/java/com/backend/global/initData/TestInitData.java
src/test/java/com/backend/domain/product/controller/ApiV1ProductControllerTest.java
src/test/java/com/backend/domain/product/service/ProductServiceTest.java

- 상품 삭제 기능 구현
- 컨트롤러 테스트, 서비스 테스트 작성/통과
Closes #24 
- 인증/인가 로직은 주석 처리했습니다
- 테스트는 BaseInitData의 work1 주석 처리하면 일단 통과합니다

[Feat]: 상품 삭제 기능 구현

---

src/main/java/com/backend/domain/bid/service/BidService.java
src/main/java/com/backend/domain/notification/service/BidNotificationService.java
src/main/java/com/backend/global/webSocket/service/WebSocketService.java
src/main/resources/static/bid-test.html

BidNotificationService: 개인 입찰 알림 관련 서비스 추가
개인 알림 관련 웹소켓 설정 추가
테스트 페이지 개인 알림 추가

[Feat]: 입찰 관련 개별알림 서비스 구현

---

docker-compose.yml
src/main/java/com/backend/domain/member/service/MemberService.java
src/main/java/com/backend/domain/product/controller/ApiV1ProductController.java
src/main/java/com/backend/domain/product/controller/ApiV1ProductControllerDocs.java
src/main/java/com/backend/domain/product/dto/ProductListByMemberDto.java
src/main/java/com/backend/domain/product/service/ProductService.java
src/main/java/com/backend/global/initData/TestInitData.java
src/main/java/com/backend/global/security/SecurityConfig.java
src/test/java/com/backend/domain/product/controller/ApiV1ProductControllerTest.java
src/test/java/com/backend/domain/product/repository/ProductRepositoryTest.java

- 특정 회원 상품 목록 조회 기능 구현
- 컨트롤러 테스트 작성/통과
- 인증/인가 로직 적용
- TestInitData 개선, 컨트롤러 및 리포지터리 테스트도 맞게 개선
Closes #27 
- docker-compose.yml 파일 만들었습니다. redis 여기에서 실행시키셔도 됩니다
- MemberService의 findMemberByEmail 메서드를 인증 로직에서 사용해야 해서 public으로 바꿨습니다
- MemberService에 findById 메서드 추가했습니다
- BaseInitData에 들어가는 데이터를 TestInitData에도 적용시켰는데, 입찰 도메인 테스트에서 오류가 아직 나는 것 같습니다

[Feat]: 특정 회원 상품 목록 조회 기능 구현

---

src/main/java/com/backend/domain/payment/controller/ApiV1PaymentMethodController.java
src/main/java/com/backend/domain/payment/repository/PaymentMethodRepository.java
src/main/java/com/backend/domain/payment/service/PaymentMethodService.java
src/test/java/com/backend/domain/payment/controller/ApiV1PaymentMethodControllerTest.java
src/test/java/com/backend/domain/payment/service/PaymentMethodServiceTest.java

- 결제 수단 단건 조회 기능 완료
- 테스트 코드 완료

[Feat}: 결제 수단 단건 조회 기능 및 테스트 코드

---

src/main/java/com/backend/domain/payment/controller/ApiV1PaymentMethodController.java
src/main/java/com/backend/domain/payment/dto/PaymentMethodEditRequest.java
src/main/java/com/backend/domain/payment/dto/PaymentMethodEditResponse.java
src/main/java/com/backend/domain/payment/repository/PaymentMethodRepository.java
src/main/java/com/backend/domain/payment/service/PaymentMethodService.java
src/test/java/com/backend/domain/payment/controller/ApiV1PaymentMethodControllerTest.java
src/test/java/com/backend/domain/payment/service/PaymentMethodServiceTest.java

[Feat]: 결제 수단 수정 기능 및 테스트 코드

---

src/main/java/com/backend/domain/product/entity/Product.java
src/main/java/com/backend/global/initData/TestInitData.java
src/main/java/com/backend/global/scheduler/AuctionSchedulerService.java
src/main/java/com/backend/global/webSocket/service/WebSocketService.java

- 경매 시작 스케줄러를 통해 상품 상태 업데이트
Closes #86

[Feat]: 경매 시작 스케줄러 구현

---

src/main/java/com/backend/global/security/SecurityConfig.java

[Feat]: CORS 설정

---

build.gradle.kts
src/main/java/com/backend/domain/member/controller/ApiV1MemberController.java
src/main/java/com/backend/domain/member/dto/MemberModifyRequestDto.java
src/main/java/com/backend/domain/member/dto/MemberMyInfoResponseDto.java
src/main/java/com/backend/domain/member/dto/MemberSignUpRequestDto.java
src/main/java/com/backend/domain/member/entity/Member.java
src/main/java/com/backend/domain/member/service/MemberService.java
src/main/resources/application-test.yml
src/test/java/com/backend/domain/member/controller/ApiV1MemberControllerTest.java
src/test/java/com/backend/global/redis/TestRedisConfiguration.java

[Feat] 내 정보 수정 기능 구현

---

.github/workflows/deploy.yml

[Fix]: gradle wrapper 권한 추가 및 에러 수정

---

src/main/java/com/backend/domain/member/controller/ApiV1MemberController.java
src/main/java/com/backend/domain/member/dto/MemberInfoResponseDto.java
src/main/java/com/backend/domain/member/service/MemberService.java
src/main/java/com/backend/global/security/SecurityConfig.java
src/test/java/com/backend/domain/member/controller/ApiV1MemberControllerTest.java

[Feat] 멤버 아이디로 멤버 정보 불러오기(판매자 정보) 기능 구현

---

src/main/java/com/backend/domain/review/controller/ApiV1ReviewController.java
src/main/java/com/backend/domain/review/dto/ReviewEditRequestDto.java
src/main/java/com/backend/domain/review/dto/ReviewEditResponseDto.java
src/main/java/com/backend/domain/review/dto/ReviewResponseDto.java
src/main/java/com/backend/domain/review/dto/ReviewWriteRequestDto.java
src/main/java/com/backend/domain/review/dto/ReviewWriteResponseDto.java
src/main/java/com/backend/domain/review/entity/Review.java
src/main/java/com/backend/domain/review/repository/ReviewRepository.java
src/main/java/com/backend/domain/review/service/ReviewService.java

[Feat] 리뷰 관련 Mock Api 기능 구현

---

.gitignore
build.gradle.kts
src/main/java/com/backend/domain/member/service/MemberService.java
src/main/java/com/backend/domain/product/service/ProductImageService.java
src/main/java/com/backend/global/aws/s3/AwsS3Config.java
src/main/java/com/backend/global/file/service/FileService.java
src/main/java/com/backend/global/file/service/LocalFileService.java
src/main/java/com/backend/global/file/service/S3FileService.java
src/main/java/com/backend/global/security/SecurityConfig.java
src/main/resources/application-prod.yml
src/test/java/com/backend/domain/member/controller/ApiV1MemberControllerTest.java
src/test/java/com/backend/domain/product/service/ProductImageServiceTest.java
src/test/java/com/backend/domain/product/service/ProductServiceTest.java
src/test/java/com/backend/global/file/service/LocalFileServiceTest.java
src/test/java/com/backend/global/file/service/S3FileServiceTest.java
terraform/main.tf

- 운영모드에서 이미지 업로드 방식을 S3 업로드로 개선
- FileService를 product 패키지에서 global로 이동
- 기존 FileService를 LocalFileService로 rename
- S3FileService에서 S3 업로드/삭제 구현
- S3FileServiceTest에서는 실제 S3 연동이 아닌, 코드의 로직이 올바른지 검증
- main.tf에 S3 버킷 설정
Closes #155 
- S3 버킷 설정 때문에 main.tf 코드 추가했습니다
- @Jiwoo-Seo main.tf를 고치면 `terraform apply` 를 해야 한다고 합니다
- 코드 변경된 부분 확인해보시고 반영 후 apply 성공하시면 말씀해주세요! merge는 그 이후에 하겠습니다

[Feat]: S3 이미지 업로드 구현

---

src/main/java/com/backend/domain/product/controller/ApiV1ProductController.java
src/main/java/com/backend/domain/product/document/ProductDocument.java
src/main/java/com/backend/domain/product/entity/Product.java
src/main/java/com/backend/domain/product/event/helper/ProductChangeTracker.java
src/main/java/com/backend/domain/product/event/listener/ProductEventListener.java
src/main/java/com/backend/domain/product/mapper/ProductMapper.java
src/main/java/com/backend/domain/product/repository/ProductElasticRepositoryImpl.java
src/main/java/com/backend/domain/product/repository/ProductRepositoryImpl.java
src/main/java/com/backend/domain/product/service/ProductImageService.java
src/main/java/com/backend/domain/product/service/ProductSearchService.java
src/main/java/com/backend/domain/product/service/ProductService.java
src/main/java/com/backend/domain/product/service/ProductSyncService.java
src/main/java/com/backend/global/file/service/FileService.java
src/main/java/com/backend/global/file/service/LocalFileService.java
src/main/java/com/backend/global/file/service/S3FileService.java
src/test/java/com/backend/domain/payment/controller/ApiV1PaymentControllerTest.java

- Product 도메인 주석 추가
- 컨트롤러, 서비스, 리포지터리 impl, 엔티티, event 관련, mapper, document, File 서비스
Closes #162 
- 전 pr에서 SecurityConfig에 인증 예외 핸들링 처리를 해서 ApiV1PaymentControllerTest에 생긴 status code 오류 정상화했습니다

[Comment]: 상품 도메인 주석 추가

---

src/main/java/com/backend/domain/bid/service/BidPaymentService.java
src/main/java/com/backend/domain/bid/service/BidService.java
src/main/java/com/backend/domain/notification/controller/ApiV1NotificationController.java
src/main/java/com/backend/domain/notification/service/NotificationService.java

1. 메소드 기능별 구분
2. RsData 정적 메소드 활용
3. 코드 간결화 및 불필요한 로직 제거
4. ServiceException 정적 메소드 활용 -> 입찰/알림 모두 적용

[Refactor]: 알림 코드 리팩토링

---

README.md
src/main/resources/application-prod.yml

[Fix]: 배포 문제 해결

---

build.gradle.kts
src/main/java/com/backend/domain/review/controller/ApiV1ReviewController.java
src/main/java/com/backend/domain/review/dto/ReviewRequest.java
src/main/java/com/backend/domain/review/dto/ReviewResponse.java
src/main/java/com/backend/domain/review/entity/Review.java
src/main/java/com/backend/domain/review/exception/ReviewException.java
src/main/java/com/backend/domain/review/repository/ReviewRepository.java
src/main/java/com/backend/domain/review/service/ReviewService.java
src/main/java/com/backend/global/response/RsStatus.java
src/test/java/com/backend/domain/review/controller/ApiV1ReviewControllerTest.java

[Feat] 리뷰 관련 API 기능 구현
